### ISSUE TITLE
Paper: compare with other approaches

### ISSUE THREAD

**Issue by odow** [adolgert/UnitTestDesign.jl#34]
The introduction should make clear that CIT is supported in other languages, e.g., Python:
 * https://damorimrg.github.io/practical_testing_book/testgeneration/combinatorial.html

You should also clarify the main contributions up front. Namely:
  * `UnitTestDesign.jl`, a Julia implementation of CIT
  * An extension to common algorithms for generating test cases. In particular:
    * Requiring certain test cases
    * Multi-level wayness
    * Forbid combinations of arguments

**Comment by adolgert** [comment]
Hey, thanks for the suggestion! I linked a pull request that changes the text to include the feature list and make a link to pairwise.org. Your suggestion made the paper better. Thanks.
